language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
before_script:
  - git clone https://github.com/neko-dev/hexo-theme-test-ci.git --depth=5
  - cd hexo-theme-test-ci
  - rm -rf .git
  - cd _hexo
  - npm install
  - git clone https://github.com/viosey/hexo-theme-material.git themes/material
  - cd themes/material
  - git checkout -t origin/canary
  - git pull
  - rm -rf .git
  - cd ..
  - cd ..
  - cd ..
  - cp -i _config.theme.yml _hexo/themes/material/_config.yml
  - cd _hexo
script:
  - hexo clean
  - hexo g
  - mkdir ./deploy-git
  - cd ./deploy-git
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEmail}"
  - git config --global user.name "${GitHubUser}"
  - git remote add origin https://${GitHubKEY}@github.com/${GitHubRepo}.git
  - git pull origin ${DeployBranch}
  - rm -rf ./*
  - cp -rf ../public/* ./
  - git add --all .
  - git commit -m "Travis Auto Tester for Material Theme"
  - git push --quiet --force https://${GitHubKEY}@github.com/${GitHubRepo}.git
  - echo "Testing..."
  - npm install selenium-webdriver
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/test.js" -O test.js
  - sed -i "s/{bs_user}/${BrowserstackUser}/g" test.js
  - sed -i "s/{bs_key}/${BrowserstackKey}/g" test.js
  - sed -i "s/{bs_project}/${BrowserstackProject}/g" test.js
  - sed -i "s/{bs_build_number}/${TRAVIS_BUILD_NUMBER}/g" test.js
  - sed -i "s/{bs_commit}/${TRAVIS_COMMIT}/g" test.js
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/OSX_Opera_12.15.js" -O OSX_Opera_12.15.js
  - node test.js OSX_Opera_12.15
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/OSX_Safari_10.0.js" -O OSX_Safari_10.0.js
  - node test.js OSX_Safari_10.0
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/w10_chrome_60.0.js" -O w10_chrome_60.0.js
  - node test.js w10_chrome_60.0
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/w10_Edge_15.js" -O w10_Edge_15.js
  - node test.js w10_Edge_15
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/w10_Firefox_54.0.js" -O w10_Firefox_54.0.js
  - node test.js w10_Firefox_54.0
  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/w10_IE_11.0.js" -O w10_IE_11.0.js
  - node test.js w10_IE_11.0
#  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/Android_GoogleNexus9_5.1.js" -O Android_GoogleNexus9_5.1.js
#  - node test.js Android_GoogleNexus9_5.1
#  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/Android_SamsungGalaxyS7_6.0.js" -O Android_SamsungGalaxyS7_6.0.js
#  - node test.js Android_SamsungGalaxyS7_6.0
#  - wget "https://raw.githubusercontent.com/neko-dev/hexo-theme-test-ci/master/config/iOS_iPhone7Plus_10.0.js" -O iOS_iPhone7Plus_10.0.js
#  - node test.js iOS_iPhone7Plus_10.0


