language: nodejs

sudo: false

cache:
  apt: true
  directories:
    - node_modules


env:
  global:
    - secure: gUVSU/Eu2rRJ4WZzvlDPseTbCIV/Nv/xNkAeSyMSqsCcdbP57y22YrArQGYLJ7UB4lNlQDDCtQTaMtoE28GCHjPWBDsX22X2hTJQxhS0fTFN9aIpPea2dcCiKTnNIS2Jh9qmV23Ly3XuI0YvDLuIs3YK9E4NtH/msz6IiUUmN9w=

branches:
  except:
  - master

branches:
  only:
  - develop

before_install:
- npm install -g hexo-cli

install:
- npm install

#after_install:

before_script:
- cd page

script:
- hexo generate

#after_script:

after_success:
- cd ..
- ./script/update-gh-pages.sh
