language: node_js
dist: trusty
node_js:
  - "7"
install:
  - npm install hexo-cli -g
before_script:
  - git clone https://github.com/neko-dev/hexo-theme-test-ci.git --depth=5
  - cd hexo-theme-test-ci
  - rm -rf .git
  - cd _hexo
  - npm install
  - git clone https://github.com/viosey/hexo-theme-material.git themes/material
  - cd themes/material
  - git checkout -t origin/canary
  - git pull
  - rm -rf .git
  - cd ..
  - cd ..
  - cd ..
  - cp -i _config.theme.yml _hexo/themes/material/_config.yml
  - cd _hexo
script:
  - hexo clean
  - hexo g
  - mkdir ./deploy-git
  - cd ./deploy-git
  - git init
  - git config --global push.default matching
  - git config --global user.email "${GitHubEmail}"
  - git config --global user.name "${GitHubUser}"
  - git remote add origin https://${GitHubKEY}@github.com/${GitHubRepo}.git
  - git pull origin ${DeployBranch}
  - rm -rf ./*
  - cp -rf ../public/* ./
  - git add --all .
  - git commit -m "Travis Auto Tester for Material Theme"
  - git push --quiet --force https://${GitHubKEY}@github.com/${GitHubRepo}.git
  - cd ..
  - cd ..
  - npm install selenium-webdriver
  - sed -i "s/{bs_user}/${BrowserstackUser}/g" test.js
  - sed -i "s/{bs_key}/${BrowserstackKey}/g" test.js
  - sed -i "s/{bs_project}/${BrowserstackProject}/g" test.js
  - sed -i "s/{bs_build_number}/${TRAVIS_BUILD_NUMBER}/g" test.js
  - sed -i "s/{bs_commit}/${TRAVIS_COMMIT}/g" test.js
  - node test.js config/OSX_Safari_10.0
  - node test.js config/w10_chrome_60.0
  - node test.js config/w10_Edge_15
  - node test.js config/w10_Firefox_54.0
  - node test.js config/w10_IE_11.0
  - node test.js config/Android_HTCOneX
  - node test.js config/Android_SamsungGalaxyS5
  - node test.js config/iOS_iPhone6SPlus


