language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"


env:
  global:
    - secure: gUVSU/Eu2rRJ4WZzvlDPseTbCIV/Nv/xNkAeSyMSqsCcdbP57y22YrArQGYLJ7UB4lNlQDDCtQTaMtoE28GCHjPWBDsX22X2hTJQxhS0fTFN9aIpPea2dcCiKTnNIS2Jh9qmV23Ly3XuI0YvDLuIs3YK9E4NtH/msz6IiUUmN9w=

branches:
  except:
    - master

branches:
  only:
    - develop

# export LC_ALL=en_US.UTF-8 &&  export LANG=en_US.UTF-8
script: pelican -o output/ -s pelicanconf.py

after_success: ./update-gh-pages.sh
