destination: ./_site
future:      true
lsi:         true
pygments:    true
permalink:   date
markdown:    rdiscount

rdiscount:
  extensions: [autolink, footnotes, generate_toc]

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'update-gh-pages.sh']

