destination: ./_site
future:      false
lsi:         true
permalink:   date
pygments:    true
markdown:    rdiscount

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'update-gh-pages.sh']

rdiscount:
  extensions: [autolink, footnotes, generate_toc]

scholar:
  style: apa
  locale: en
  source: ./_bibliography
  bibliography: references.bib

  details_dir:    bibliography
  details_layout: bibliography_detail.html
  details_link: '>>'
  query: "@*"


