destination: ./_site
lsi:         true
pygments:    true
markdown:    rdiscount
permalink:   date
rdiscount:
  extensions: [smart]

exclude:
- README.md

tag_page_dir:    tag
tag_page_layout: tag_page
